/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.time.LocalDate;
import java.time.Year;
import java.time.temporal.ChronoUnit;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JSpinner;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

/**
 *
 * @author Saputra
 */
public class AplikasiPerhitunganHari extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPerhitunganHari
     */
    public AplikasiPerhitunganHari() {
        initComponents();
        // Menambahkan PropertyChangeListener untuk jCalendar1
        jCalendar1.addPropertyChangeListener("calendar", new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                // Memperbarui model spinTahun saat tanggal di jCalendar1 berubah
                updateSpinTahun();
            }
        });
        // Inisialisasi spinTahun pertama kali
        updateSpinTahun();
        // Mengatur editor spinTahun agar hanya menampilkan angka bulat
        JSpinner.NumberEditor editor = new JSpinner.NumberEditor(spinTahun, "#");
        spinTahun.setEditor(editor);
    }

    private void updateSpinTahun() {
        // Mendapatkan tahun dari jCalendar1
        int selectedYear = jCalendar1.getDate().toInstant()
                .atZone(java.time.ZoneId.systemDefault())
                .toLocalDate().getYear();
        // Membuat model spinner dengan rentang tahun
        int startYear = selectedYear - 10;
        int endYear = selectedYear + 10;
        spinTahun.setModel(new javax.swing.SpinnerNumberModel(selectedYear, startYear, endYear, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        boxBulan = new javax.swing.JComboBox<>();
        spinTahun = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        btnHasil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaHasil = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 15, 0, 15, 0};
        jPanel1Layout.rowHeights = new int[] {0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setText("Masukan Tanggal Awal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        jPanel1.add(jCalendar1, gridBagConstraints);

        boxBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(boxBulan, gridBagConstraints);

        spinTahun.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinTahunStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(spinTahun, gridBagConstraints);

        jLabel2.setText("Masukan Tanggal Berikutnya");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        jPanel1.add(jLabel2, gridBagConstraints);

        btnHasil.setText("Hitung!");
        btnHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHasilActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel1.add(btnHasil, gridBagConstraints);

        areaHasil.setColumns(20);
        areaHasil.setRows(5);
        jScrollPane1.setViewportView(areaHasil);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 50;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jLabel4.setText("Hasil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        jPanel1.add(jLabel4, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHasilActionPerformed
        // Mendapatkan tanggal awal dari jCalendar1
        LocalDate dateAwal = jCalendar1.getDate().toInstant()
                .atZone(java.time.ZoneId.systemDefault())
                .toLocalDate();

        // Mendapatkan bulan dan tahun dari input pengguna
        int bulan = boxBulan.getSelectedIndex() + 1; // Indeks mulai dari 0
        int tahun = (int) spinTahun.getValue();

        // Membuat objek LocalDate dengan tanggal 1 di bulan dan tahun yang dipilih
        LocalDate dateAkhir = LocalDate.of(tahun, bulan, 1);

        // Menghitung jumlah hari antara dua tanggal
        long jumlahHari = ChronoUnit.DAYS.between(dateAwal, dateAkhir);

        // Mengecek apakah tahun kabisat
        boolean isLeapYear = Year.isLeap(tahun);

        // Mendapatkan hari pertama dan terakhir dalam bulan dateAkhir
        LocalDate firstDayOfMonthAkhir = dateAkhir.withDayOfMonth(1);
        LocalDate lastDayOfMonthAkhir = dateAkhir.withDayOfMonth(dateAkhir.lengthOfMonth());

        // Mendapatkan hari pertama dan terakhir dalam bulan dateAwal
        LocalDate firstDayOfMonthAwal = dateAwal.withDayOfMonth(1);
        LocalDate lastDayOfMonthAwal = dateAwal.withDayOfMonth(dateAwal.lengthOfMonth());

        // Formatter untuk menampilkan nama hari dalam bahasa Indonesia
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE", new Locale("id", "ID"));

        String hariPertamaAwal = firstDayOfMonthAwal.format(formatter);
        String hariTerakhirAwal = lastDayOfMonthAwal.format(formatter);

        String hariPertamaAkhir = firstDayOfMonthAkhir.format(formatter);
        String hariTerakhirAkhir = lastDayOfMonthAkhir.format(formatter);

        // Menampilkan hasil pada areaHasil
        areaHasil.setText(
            "Tanggal Awal: " + dateAwal + "\n" +
            "Hari pertama pada bulan " + dateAwal.getMonth() + " tahun " + dateAwal.getYear() + " adalah " +
            hariPertamaAwal + ".\n" +
            "Hari terakhir pada bulan " + dateAwal.getMonth() + " tahun " + dateAwal.getYear() + " adalah " +
            hariTerakhirAwal + ".\n\n" +
            "Tanggal Akhir: " + dateAkhir + "\n" +
            "Hari pertama pada bulan " + boxBulan.getSelectedItem() + " tahun " + tahun + " adalah " +
            hariPertamaAkhir + ".\n" +
            "Hari terakhir pada bulan " + boxBulan.getSelectedItem() + " tahun " + tahun + " adalah " +
            hariTerakhirAkhir + ".\n\n" +
            "Jumlah hari antara " + dateAwal + " dan " + dateAkhir + " adalah " +
            Math.abs(jumlahHari) + " hari.\n" +
            "Tahun " + tahun + (isLeapYear ? " adalah " : " bukan ") + "tahun kabisat."
        );
    }//GEN-LAST:event_btnHasilActionPerformed

    private void spinTahunStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinTahunStateChanged
        // Mendapatkan nilai tahun yang baru dari spinTahun
        int tahun = (int) spinTahun.getValue();

        // Membersihkan area hasil
        areaHasil.setText("");

        // Jika diperlukan, perbarui komponen atau lakukan perhitungan otomatis
        // Contoh: Memanggil metode perhitungan otomatis
        // hitungSelisihHari();
    }//GEN-LAST:event_spinTahunStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPerhitunganHari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaHasil;
    private javax.swing.JComboBox<String> boxBulan;
    private javax.swing.JButton btnHasil;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinTahun;
    // End of variables declaration//GEN-END:variables
}
